version: '3'
services:
  web:
    image: todo-list:v0.0.1
    ports:
      - "80:8080"
    depends_on:
      - db
  db:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
