---
- name: git clone task
  hosts: web
  tasks:
    - name: check if git installed
      ignore_errors: yes
      command: which git
      register: check_git_result
    
    - name: debug git command existed
      debug:
        var: check_git_result
    
    - name: install git if not existed
      apt: 
        name: git
        state: latest
      when: check_git_result.stderr != ""

    - name: clone nodejs repository
      git:
        repo: https://github.com/handuy/nodejs-todolist
        dest: ~/mycode/nodejs-todolist 